routes:

collections:
  /:
    permalink: "/{slug}/"
    template: index
    filter: tag:-[layanan,pph,ppn,kup]
  /pph/:
    permalink: /pph/{slug}/
    template: tax-knowledgebase
    filter: primary_tag:pph

taxonomies:
  tag: "/{slug}/"
  author: "/{slug}/"
